# Workshop 13: Linear algebra with Python

## Learning Outcomes

By the end of this workshop you will:
 * understand how to use 2d arrays to solve linear algebra problems
 * be able to write a simple routine to solve a system of n equations
 * know how to use the linear solver from the SciPy package
 
## Linear algebra

One of the great things about computers is that they are good at doing tasks accurately and repeatedly, and not getting bored with doing them -- unlike humans! As such, they are good for tackling a lot of mathematics problems that a human could potentially solve but would not really want to. For example, you should be able to solve the following pair of linear algebraic equations:
$$
2x + 3y = 8
$$
$$
-x + y = 1
$$
and find that $x=1, y=2$. But if you were given 20 equations with 20 unknowns, you would no doubt find it tedious and if you are anything like me, you would make a handful of mistakes in the process. It is far better that we get the computer to do it for us. That is what we will be looking at today.

### Introduction: arrays and their manipulation

Before we start on the details of how to solve linear systems of equations, we need to be familiar with arrays as we will ultimately be putting the coefficients of our equations into these structures so that we can work with them.

Arrays are a form of data structure provided by the NumPy (Numerical Python) package, which we first need to import:

In [2]:
import numpy as np

We can then use NumPy's `array` function to create familiar structures like vectors and matrices. In both cases, these need to be 2d structures, not simply 1d arrays. For the idea of row and column vectors to make sense, we need information on both the number of rows and the number of columns (even if the number is only 1!). So to express the row and column vectors:
$$
a = \begin{bmatrix} 1 & -2 & 4 \end{bmatrix}, b = \begin{bmatrix} 3 \\ 1 \\ -1 \end{bmatrix},
$$
we use the following:

In [3]:
# note the number and placement of the square brackets!
a = np.array([[1, -2, 4]]) 
b = np.array([[3],[1],[-1]])

print(np.shape(a))
print(np.shape(b))

(1, 3)
(3, 1)


We can now perform any of our usual mathematical operations on our vectors, such as multiplying by scalars, adding and subtracting vectors/matrices with the same dimensions. We can also multiply and divide, remembering that:
$$
\begin{bmatrix} a_{00} & a_{01} \\ a_{10} & a_{11} \end{bmatrix}\begin{bmatrix} x_0 \\ x_1\end{bmatrix}
= \begin{bmatrix} a_{00}x_0 + a_{01}x_1 \\ a_{10}x_0 + a_{11}x_1 \end{bmatrix}
$$ 

This last form is particularly helpful to us, as it is how we are going to express our systems of linear equations.  We can express any system of linear equations as a product of a matrix containing the coefficients of the variables of our equations, mulitplying a column vector of the variables themselves. Thus for the example pair of equations I used at the beginning, we can write:
$$
2x + 3y = 8
$$
$$
-x + y = 1
$$
as
$$
\begin{bmatrix}2 & 3 \\ -1 & 1\end{bmatrix}\begin{bmatrix}x \\ y\end{bmatrix}
= \begin{bmatrix} 8 \\ 1 \end{bmatrix}
$$

How do we actually solve these equations? What I really mean to ask is what is the *method* by which we solve them? The first step in computing is always to identify the algorithm you are going to use.

One approach is called Gaussian Elimination. It involves using one equation to eliminate one unknown in the remaining equations. You can then repeat the processes until you finally end up with an equation with only one variable in it. You can then find the rest by a process of back substitution. Here's how we do it:

#### Step 1:

Select which equation we want to use to eliminate the first variable (I will choose to do this for $x$ first). We call this the pivot equation, and we typically choose the equation that has the largest coefficient for that variable (why?). Here we'll choose $2x+3y = 8$ as the pivot.

#### Step 2:

Divide the pivot equation by the value of coefficient of the variable we are going to eliminate. In this case, we divide by 2, giving $x + 1.5y = 4$.

#### Step 3:

Multiply our new equation by whatever the coefficient of $x$ is in the second equation, and subtract the result from the second equation. This gives us $2.5y = 5$.

#### Step 4:

Solve for y. This gives us $y = 2$

#### Step 5:

Now for the back substitution. We had $x + 1.5y = 4$, so use this with our value of $y$ to obtain $x$. We get $x = 1$.

## Exercise 1

Now convert the above steps into a Python code to do the solution for you. Put the coefficients into a 2x2 2-d array, `A`, and the right-hand side values into a 1x2 2-d array `b`, i.e.:

$$
\mathbf{A} = \begin{bmatrix}2 & 3 \\ -1 & 1\end{bmatrix}, \ \ 
\mathbf{b} = \begin{bmatrix} 8 \\ 1 \end{bmatrix}
$$

It is important that you enter each coefficient as a `float` and not an `int` -- we are going to do operations that result in non-integer values, so our arrays need to be arrays of floats.

We also need to create a 1x2 2-d array to put our solution in. We will call this array `x`.

Essentially we will be solving the matrix equation:
$$
\mathbf{A}\mathbf{x} = \mathbf{b}.
$$

First create the necessary arrays A and b. Also, create a 2x1 array of zeros, as we will need this to put the solution in.

In [3]:
A = np.array([[2.0, 3.0],[-1.0, 1.0]])
b = np.array([[8.0],[1.0]])

x = np.array([[0.0],[0.0]])

(2, 1)

Divide the first row of both the A and b arrays by whatever the value in the first row and column of the array `A`, i.e. the value `A[0][0]`. Be sure to check the result is what you expect it to be!

In [34]:
# set the pivot
pivot = A[0][0]

# iterate on the first row for A
A[0][:] = A[0][:]/pivot
# iterate on the first row for b
b[0] = b[0]/pivot

Now take the second row in `A` and subtract `A[1][0]` multiplied by the first row. Do the same for `b`. Again, check the result is what you expect.

In [35]:
# set the coefficient
coeff = A[1][0]

# iterate on the second row for A
A[1][:] = A[1][:] - coeff*A[0][:]

# iterate on the second row for b
b[1] = b[1] - coeff*b[0]

The second row of `A` should now contain a zero in the first column, so we can divide `b[1]` by the remaining non-zero coefficient in `A` to get the value of `x[1]`:

In [37]:
x[1] = b[1]/A[1][1]

Now use the value of `x[1]` and the coefficients in the first row of `A` to find `x[0]`:

In [39]:
x[0] = b[0] - A[0][1]*x[1]

Check that `x` contains the correct solution:

In [40]:
x

array([[1.],
       [2.]])

You now have code that you can put into a function, so that if you supply it with the array of coefficients, `A`, and the right-hand sides of the equations, `b`, it will return the solution `x`.

In [51]:
def solve_2d(A,b):
    # set empty solution array
    x = np.array([[0.0],[0.0]])
    
    # Routine to solve 2 simultaneous equations with two unknowns
    # set the pivot
    pivot = A[0][0]

    # iterate on the first row for A
    A[0][:] = A[0][:]/pivot
    # iterate on the first row for b
    b[0] = b[0]/pivot
    
    # set the coefficient
    coeff = A[1][0]

    # iterate on the second row for A
    A[1][:] = A[1][:] - coeff*A[0][:]

    # iterate on the second row for b
    b[1] = b[1] - coeff*b[0]
    
    # solve for the last component of x
    x[1] = b[1]/A[1][1]
    
    # back substitute to get the next
    x[0] = b[0] - A[0][1]*x[1]
    
    return x

Use your function to solve the equations:

$$
 5x - 3y = 1
$$
$$
2x + y = 7
$$

In [50]:
C = np.array([[5.0, -3.0],[2.0, 1.0]])
d = np.array([[1.0],[7.0]])

solve_2d(C,d)

[[ 1.  -0.6]
 [ 2.   1. ]]
[[ 1.  -0.6]
 [ 0.   2.2]]


array([[2.],
       [3.]])

#### Generalization

This is all well and good, but solving for just two unknowns is trivial and we can probably do it quicker by hand than we can code it up. We really want a method for solving a system of n equations for n unknowns. In order to do this, we need to think about the _algorithm_ that lies behind the method. What are the steps we need to take in order to obtain our solution?

What we did for just two equations was to eliminate a variable from one of the equations using a multipe of the other. For multiple equations, we do exactly the same thing though we will need to use a combination of all the other equations. Suppose our system of equations takes the form:
$$
\begin{bmatrix} a_{00} & a_{01} & a_{02} & \cdots & a_{0n} \\ a_{10} & a_{11} & a_{12} & \cdots & a_{1n} \\ a_{20} & a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \vdots& \ddots & \vdots \\ a_{n0} & a_{n1} & a_{n2} & \cdots & a_{nn} \end{bmatrix}\begin{bmatrix}x_0 \\ x_1 \\ x_2 \\ \vdots \\ x_n\end{bmatrix} = \begin{bmatrix}b_0 \\ b_1 \\ b_2 \\ \vdots \\ b_n\end{bmatrix}.
$$
If we can manipulate each row of the equations so that we can get the matrix equation into the form:
$$
\begin{bmatrix}
 1 & a'_{01} & a'_{02} & \cdots & a'_{0n} \\
 0 & 1 & a'_{12} & \cdots & a'_{1n} \\
 0 & 0 & 1 & \cdots & a'_{2n} \\
 \vdots & \vdots & \vdots & \ddots & \vdots \\
 0 & 0 & 0 & \cdots & 1 \\
\end{bmatrix}
\begin{bmatrix}x_0 \\ x_1 \\ x_2 \\ \vdots \\ x_n\end{bmatrix} =
\begin{bmatrix}b'_0 \\ b'_1 \\ b'_2 \\ \vdots \\ b'_n\end{bmatrix}.
$$
then we can solve our problem. The last row gives us the value of $x_n$, and we can use back substitution to find the value of $x_{n-1}$ usinig the $n-1$th row, and so forth.

Here are the steps we should take:

##### Step 1
Divide the first row of our set of equation by $a_{00}$. This gives:

$$
\begin{bmatrix} 1 & a'_{01} & a'_{02} & \cdots & a'_{0n} \\ a_{10} & a_{11} & a_{12} & \cdots & a_{1n} \\ a_{20} & a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \vdots& \ddots & \vdots \\ a_{n0} & a_{n1} & a_{n2} & \cdots & a_{nn} \end{bmatrix}
\begin{bmatrix}x_0 \\ x_1 \\ x_2 \\ \vdots \\ x_n\end{bmatrix} = \begin{bmatrix}b'_0 \\ b_1 \\ b_2 \\ \vdots \\ b_n\end{bmatrix}.
$$

##### Step 2
For the remaining m rows, subtract $a_{m0}$ times the first row from each equation. This gets us to:

$$
\begin{bmatrix} 1 & a'_{01} & a'_{02} & \cdots & a'_{0n} \\ 0 & a'_{11} & a'_{12} & \cdots & a'_{1n} \\ 0 & a'_{21} & a'_{22} & \cdots & a'_{2n} \\ \vdots & \vdots & \vdots& \ddots & \vdots \\ 0 & a'_{n1} & a'_{n2} & \cdots & a'_{nn} \end{bmatrix}
\begin{bmatrix}x_0 \\ x_1 \\ x_2 \\ \vdots \\ x_n\end{bmatrix} = \begin{bmatrix}b'_0 \\ b'_1 \\ b'_2 \\ \vdots \\ b'_n\end{bmatrix}.
$$

##### Step 3

Now divide the second row by $a'_{11}$, so that we have a $1$ in the second column of the second row:
$$
\begin{bmatrix} 1 & a'_{01} & a'_{02} & \cdots & a'_{0n} \\ 0 & 1 & a''_{12} & \cdots & a''_{1n} \\ 0 & a'_{21} & a'_{22} & \cdots & a'_{2n} \\ \vdots & \vdots & \vdots& \ddots & \vdots \\ 0 & a'_{n1} & a'_{n2} & \cdots & a'_{nn} \end{bmatrix}
\begin{bmatrix}x_0 \\ x_1 \\ x_2 \\ \vdots \\ x_n\end{bmatrix} = \begin{bmatrix}b'_0 \\ b''_1 \\ b'_2 \\ \vdots \\ b'_n\end{bmatrix}.
$$

##### Step 4

Just as we did in step 2, we can use our new second row to elimate all the $a_{m1}$ coefficients in the remaining rows:
$$
\begin{bmatrix} 1 & a'_{01} & a'_{02} & \cdots & a'_{0n} \\ 0 & 1 & a''_{12} & \cdots & a''_{1n} \\ 0 & 0 & a''_{22} & \cdots & a''_{2n} \\ \vdots & \vdots & \vdots& \ddots & \vdots \\ 0 & 0 & a''_{n2} & \cdots & a''_{nn} \end{bmatrix}
\begin{bmatrix}x_0 \\ x_1 \\ x_2 \\ \vdots \\ x_n\end{bmatrix} = \begin{bmatrix}b'_0 \\ b''_1 \\ b''_2 \\ \vdots \\ b''_n\end{bmatrix}.
$$


##### Step 5

Use the same idea to reduce each row in turn until we get we have a 1 in the final column of the last row:
$$
\begin{bmatrix}
 1 & a'_{01} & a'_{02} & \cdots & a'_{0n} \\
 0 & 1 & a'_{12} & \cdots & a'_{1n} \\
 0 & 0 & 1 & \cdots & a'_{2n} \\
 \vdots & \vdots & \vdots & \ddots & \vdots \\
 0 & 0 & 0 & \cdots & 1 \\
\end{bmatrix}
\begin{bmatrix}x_0 \\ x_1 \\ x_2 \\ \vdots \\ x_n\end{bmatrix} =
\begin{bmatrix}b'_0 \\ b'_1 \\ b'_2 \\ \vdots \\ b'_n\end{bmatrix}.
$$
This gives us the value of $x_n$.

##### Step 6

Begin the process of back substitution. Insert the value of $x_n$ into the $n-1$th row, and solve for $x_{n-1}$. Repeat for each remaining row.

### Exercise 2

Now try coding up the above algorithm. Assume that you have the coefficients $a$ in a single 2d $n$x$n$ array `A`, and the $b$ values in a single 1x$n$ array `b`. You might find it easiest to work with a specific case in mind so that you can check your steps are correct as you go. I have started you off with an example of solving 3 specific equations:
$$
x + y + z = 2 \\
3x -2y - 2z = 1 \\
2x +3y + z = -1
$$

Make sure your algorithm can deal with arbitrary n!

In [108]:
# set the number of equations to solve
n = 3

# create an empty solution array
x = np.zeros(shape=(n))

# Input the array of A values
A = np.array([[1.0, 1.0, 1.0], [3.0, -2.0, -2.0], [2.0, 3.0, 1.0]])

# Input the array of b values
b = np.array([2.0, 1.0, -1.0])

In [109]:
# Perform the elimination

# go through each row in turn
for i in range(0,n):
    # select the pivot
    pivot = A[i, i]
    for j in range(i,n):
        # divide through each column by the pivot
        A[i, j] = A[i,j]/pivot
    # Also divide the relevant b value by the pivot
    b[i] = b[i]/pivot

    # subtract a multiple of the ith row from each remaining row
    for k in range(i+1,n):
        multiple = A[k,i] 
        for j in range(i,n):
            # A[i,j] is the coefficent of the jth column in the ith row
            A[k,j] = A[k,j]-multiple*A[i,j]
        b[k] = b[k]-multiple*b[i]

In [110]:
# perform the back substitution

# the last value of b is the nth x-value
for k in range(0,n):
    # use kk to count backwards from n to 0
    kk = n - (k+1)
    # kk = n is the last value
    if kk == n:
        x[kk] = b[kk]
    else:
        sum = 0.0
        for j in range(kk+1,n):
            sum += A[kk,j]*x[j]
        x[kk] = b[kk] - sum
        
print(x)

[ 1. -2.  3.]


Now invent a simple test case involving 5 equations, and test your algorithm on it.

The algorithm is pretty basic, and not without its flaws. Can you think of conditions where it might break down? What might you decide to include to prevent this (in theory! Don't try and code it)? Are there any other improvements that could be made?

Our algorithm doesn't check if the pivot is zero before proceeding. If it is, then we can always switch the columns or rows around to choose a non-zero pivot. We will need to make sure we remember any such switches when we do the back substitution.

Another trick is to always choose the largest pivot possible -- dividing by small numbers can cause all sorts of problems. Again, we can shift the order of the columns to always have the largest pivot for a given row.

More details on the methods we have discussed here can be found in chapter 2 of [Numerical Recipes](http://numerical.recipes/book/book.html), together with some more advanced methods for solving linear equations.

## Scientific Python for Linear Algebra

One of the great things about working with python is the wealth of modules that are available for it. If you want to perfom any moderately-common task, there is a good chance that there is an already written python module that will do exactly what you want. Many of the tools we need for numerical methods are contained within the handy Scientific Python or SciPy module. You can find the documentation for the module [here](https://scipy.github.io/devdocs/tutorial/index.html). There are a range of functions and routines included in SciPy: for now we only concern ourselves with the linear algebra part of the package, `linalg`.

We import the package in the usual way:

In [98]:
from scipy import linalg

`linalg` contains many routines for dealing with matrices and operations involving them. It also contains the handy routine `solve` which can be used to solve systems of linear equations, just like we did above. If we have the coefficients of our variables in an nxn 2d-array, `A`, and the right-hand side of our equations in a nx1 array, we can invoke the solver as follows:

In [99]:
# To solve the equations:
# 5x - 3y = 1, 2x + y =7

A = np.array([[5.0, -3.0],[2.0, 1.0]])
b = np.array([[1.0],[7.0]])

linalg.solve(A,b)

array([[2.],
       [3.]])

### Exercise 3

Try to solve the following equations using your own solver from exercise 2:
$$
x + 2y - z = 6 \\
2x + 4y -3z = 11 \\
-2x + y + 5z = 1
$$
You should find that you get a divide by zero error, because subtracting twice the first row from the second results in a zero for the pivot.

Now try solving the same set of equations with `linalg.solve`.

In [102]:
A = np.array([[1.0, 2.0, -1],[2.0, 4.0, -3.0],[-2.0, 1.0, 5.0]])
b = np.array([[6.0],[11.0],[1.0]])

linalg.solve(A,b)

array([[3.],
       [2.],
       [1.]])

This returns a result without errors -- `linalg.solve` is a much better solver than the one we wrote, and can handle some of the exceptions we discussed above.